// Code generated by goctl. DO NOT EDIT.
// Source: information.proto

package server

import (
	"context"

	"go-micro/platform/information/rpc/information"
	"go-micro/platform/information/rpc/internal/logic/informationtopicauditrecordservice"
	"go-micro/platform/information/rpc/internal/svc"
)

type InformationTopicAuditRecordServiceServer struct {
	svcCtx *svc.ServiceContext
	information.UnimplementedInformationTopicAuditRecordServiceServer
}

func NewInformationTopicAuditRecordServiceServer(svcCtx *svc.ServiceContext) *InformationTopicAuditRecordServiceServer {
	return &InformationTopicAuditRecordServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加文章审核记录
func (s *InformationTopicAuditRecordServiceServer) AddTopicAuditRecord(ctx context.Context, in *information.AddTopicAuditRecordRequest) (*information.AddTopicAuditRecordResponse, error) {
	l := informationtopicauditrecordservicelogic.NewAddTopicAuditRecordLogic(ctx, s.svcCtx)
	return l.AddTopicAuditRecord(in)
}

// 获取文章审核记录
func (s *InformationTopicAuditRecordServiceServer) GetTopicAuditRecord(ctx context.Context, in *information.GetTopicAuditRecordRequest) (*information.GetTopicAuditRecordResponse, error) {
	l := informationtopicauditrecordservicelogic.NewGetTopicAuditRecordLogic(ctx, s.svcCtx)
	return l.GetTopicAuditRecord(in)
}
