// Code generated by goctl. DO NOT EDIT.
// Source: basic.proto

package server

import (
	"context"

	"go-micro/platform/basic/rpc/basic"
	"go-micro/platform/basic/rpc/internal/logic/basicservice"
	"go-micro/platform/basic/rpc/internal/svc"
)

type BasicServiceServer struct {
	svcCtx *svc.ServiceContext
	basic.UnimplementedBasicServiceServer
}

func NewBasicServiceServer(svcCtx *svc.ServiceContext) *BasicServiceServer {
	return &BasicServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *BasicServiceServer) Ping(ctx context.Context, in *basic.Request) (*basic.Response, error) {
	l := basicservicelogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
