// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	newsFieldNames          = builder.RawFieldNames(&News{})
	newsRows                = strings.Join(newsFieldNames, ",")
	newsRowsExpectAutoSet   = strings.Join(stringx.Remove(newsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	newsRowsWithPlaceHolder = strings.Join(stringx.Remove(newsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheNewsIdPrefix = "cache:news:id:"
)

type (
	newsModel interface {
		Insert(ctx context.Context, data *News) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*News, error)
		Update(ctx context.Context, data *News) error
		Delete(ctx context.Context, id int64) error
	}

	defaultNewsModel struct {
		sqlc.CachedConn
		table string
	}

	News struct {
		Id        int64          `db:"id"`
		Title     string         `db:"title"`      // 标题
		Img       string         `db:"img"`        // 首图
		Content   sql.NullString `db:"content"`    // 内容
		Status    int64          `db:"status"`     // 状态
		UserId    int64          `db:"user_id"`    // 用户id
		AuditorId int64          `db:"auditor_id"` // 审核者id
		CreatedAt time.Time      `db:"created_at"` // 创建时间
		UpdatedAt time.Time      `db:"updated_at"` // 更新时间
		AuditedAt sql.NullTime   `db:"audited_at"` // 审核时间
		DeletedAt sql.NullTime   `db:"deleted_at"` // 删除时间
	}
)

func newNewsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultNewsModel {
	return &defaultNewsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`news`",
	}
}

func (m *defaultNewsModel) Delete(ctx context.Context, id int64) error {
	newsIdKey := fmt.Sprintf("%s%v", cacheNewsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, newsIdKey)
	return err
}

func (m *defaultNewsModel) FindOne(ctx context.Context, id int64) (*News, error) {
	newsIdKey := fmt.Sprintf("%s%v", cacheNewsIdPrefix, id)
	var resp News
	err := m.QueryRowCtx(ctx, &resp, newsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", newsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNewsModel) Insert(ctx context.Context, data *News) (sql.Result, error) {
	newsIdKey := fmt.Sprintf("%s%v", cacheNewsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, newsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Title, data.Img, data.Content, data.Status, data.UserId, data.AuditorId, data.AuditedAt, data.DeletedAt)
	}, newsIdKey)
	return ret, err
}

func (m *defaultNewsModel) Update(ctx context.Context, data *News) error {
	newsIdKey := fmt.Sprintf("%s%v", cacheNewsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, newsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Title, data.Img, data.Content, data.Status, data.UserId, data.AuditorId, data.AuditedAt, data.DeletedAt, data.Id)
	}, newsIdKey)
	return err
}

func (m *defaultNewsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheNewsIdPrefix, primary)
}

func (m *defaultNewsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", newsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultNewsModel) tableName() string {
	return m.table
}
