// Code generated by goctl. DO NOT EDIT.
// Source: basic.proto

package basicstageservice

import (
	"context"

	"go-micro/platform/basic/rpc/basic"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCategoryRequest             = basic.AddCategoryRequest
	AddCategoryResponse            = basic.AddCategoryResponse
	AddClassifyRequest             = basic.AddClassifyRequest
	AddClassifyResponse            = basic.AddClassifyResponse
	AddConfigurationRequest        = basic.AddConfigurationRequest
	AddConfigurationResponse       = basic.AddConfigurationResponse
	AddIndustryRequest             = basic.AddIndustryRequest
	AddIndustryResponse            = basic.AddIndustryResponse
	AddRegionRequest               = basic.AddRegionRequest
	AddRegionResponse              = basic.AddRegionResponse
	AddStageRequest                = basic.AddStageRequest
	AddStageResponse               = basic.AddStageResponse
	Configuration                  = basic.Configuration
	DeleteCategoryRequest          = basic.DeleteCategoryRequest
	DeleteCategoryResponse         = basic.DeleteCategoryResponse
	DeleteClassifyRequest          = basic.DeleteClassifyRequest
	DeleteClassifyResponse         = basic.DeleteClassifyResponse
	DeleteConfigurationRequest     = basic.DeleteConfigurationRequest
	DeleteConfigurationResponse    = basic.DeleteConfigurationResponse
	DeleteIndustryRequest          = basic.DeleteIndustryRequest
	DeleteIndustryResponse         = basic.DeleteIndustryResponse
	DeleteRegionRequest            = basic.DeleteRegionRequest
	DeleteRegionResponse           = basic.DeleteRegionResponse
	DeleteStageRequest             = basic.DeleteStageRequest
	DeleteStageResponse            = basic.DeleteStageResponse
	GetCategoriesRequest           = basic.GetCategoriesRequest
	GetCategoriesResponse          = basic.GetCategoriesResponse
	GetCategoryChild               = basic.GetCategoryChild
	GetCategoryRequest             = basic.GetCategoryRequest
	GetCategoryResponse            = basic.GetCategoryResponse
	GetClassifiesRequest           = basic.GetClassifiesRequest
	GetClassifiesResponse          = basic.GetClassifiesResponse
	GetClassifyChild               = basic.GetClassifyChild
	GetClassifyRequest             = basic.GetClassifyRequest
	GetClassifyResponse            = basic.GetClassifyResponse
	GetConfigurationByNameRequest  = basic.GetConfigurationByNameRequest
	GetConfigurationRequest        = basic.GetConfigurationRequest
	GetConfigurationResponse       = basic.GetConfigurationResponse
	GetConfigurationsRequest       = basic.GetConfigurationsRequest
	GetConfigurationsResponse      = basic.GetConfigurationsResponse
	GetIndustriesRequest           = basic.GetIndustriesRequest
	GetIndustriesResponse          = basic.GetIndustriesResponse
	GetIndustryByIndustryIdRequest = basic.GetIndustryByIndustryIdRequest
	GetIndustryChild               = basic.GetIndustryChild
	GetIndustryRequest             = basic.GetIndustryRequest
	GetIndustryResponse            = basic.GetIndustryResponse
	GetRegionChild                 = basic.GetRegionChild
	GetRegionRequest               = basic.GetRegionRequest
	GetRegionResponse              = basic.GetRegionResponse
	GetRegionsRequest              = basic.GetRegionsRequest
	GetRegionsResponse             = basic.GetRegionsResponse
	GetStageChild                  = basic.GetStageChild
	GetStageRequest                = basic.GetStageRequest
	GetStageResponse               = basic.GetStageResponse
	GetStagesRequest               = basic.GetStagesRequest
	GetStagesResponse              = basic.GetStagesResponse
	Request                        = basic.Request
	Response                       = basic.Response
	UpdateCategoryRequest          = basic.UpdateCategoryRequest
	UpdateCategoryResponse         = basic.UpdateCategoryResponse
	UpdateClassifyRequest          = basic.UpdateClassifyRequest
	UpdateClassifyResponse         = basic.UpdateClassifyResponse
	UpdateConfigurationRequest     = basic.UpdateConfigurationRequest
	UpdateConfigurationResponse    = basic.UpdateConfigurationResponse
	UpdateIndustryRequest          = basic.UpdateIndustryRequest
	UpdateIndustryResponse         = basic.UpdateIndustryResponse
	UpdateRegionRequest            = basic.UpdateRegionRequest
	UpdateRegionResponse           = basic.UpdateRegionResponse
	UpdateStageRequest             = basic.UpdateStageRequest
	UpdateStageResponse            = basic.UpdateStageResponse

	BasicStageService interface {
		// 获取阶段信息
		GetStage(ctx context.Context, in *GetStageRequest, opts ...grpc.CallOption) (*GetStageResponse, error)
		// 根据父级id获取阶段信息
		GetStages(ctx context.Context, in *GetStagesRequest, opts ...grpc.CallOption) (*GetStagesResponse, error)
		// 添加阶段信息
		AddStage(ctx context.Context, in *AddStageRequest, opts ...grpc.CallOption) (*AddStageResponse, error)
		// 更新阶段信息
		UpdateStage(ctx context.Context, in *UpdateStageRequest, opts ...grpc.CallOption) (*UpdateStageResponse, error)
		// 删除阶段信息
		DeleteStage(ctx context.Context, in *DeleteStageRequest, opts ...grpc.CallOption) (*DeleteStageResponse, error)
	}

	defaultBasicStageService struct {
		cli zrpc.Client
	}
)

func NewBasicStageService(cli zrpc.Client) BasicStageService {
	return &defaultBasicStageService{
		cli: cli,
	}
}

// 获取阶段信息
func (m *defaultBasicStageService) GetStage(ctx context.Context, in *GetStageRequest, opts ...grpc.CallOption) (*GetStageResponse, error) {
	client := basic.NewBasicStageServiceClient(m.cli.Conn())
	return client.GetStage(ctx, in, opts...)
}

// 根据父级id获取阶段信息
func (m *defaultBasicStageService) GetStages(ctx context.Context, in *GetStagesRequest, opts ...grpc.CallOption) (*GetStagesResponse, error) {
	client := basic.NewBasicStageServiceClient(m.cli.Conn())
	return client.GetStages(ctx, in, opts...)
}

// 添加阶段信息
func (m *defaultBasicStageService) AddStage(ctx context.Context, in *AddStageRequest, opts ...grpc.CallOption) (*AddStageResponse, error) {
	client := basic.NewBasicStageServiceClient(m.cli.Conn())
	return client.AddStage(ctx, in, opts...)
}

// 更新阶段信息
func (m *defaultBasicStageService) UpdateStage(ctx context.Context, in *UpdateStageRequest, opts ...grpc.CallOption) (*UpdateStageResponse, error) {
	client := basic.NewBasicStageServiceClient(m.cli.Conn())
	return client.UpdateStage(ctx, in, opts...)
}

// 删除阶段信息
func (m *defaultBasicStageService) DeleteStage(ctx context.Context, in *DeleteStageRequest, opts ...grpc.CallOption) (*DeleteStageResponse, error) {
	client := basic.NewBasicStageServiceClient(m.cli.Conn())
	return client.DeleteStage(ctx, in, opts...)
}
