// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-micro/platform/gateway/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/gateway/region/:id",
				Handler: getRegionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/gateway/regions/:parent_id",
				Handler: getRegionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/gateway/region",
				Handler: addRegionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/gateway/register",
				Handler: registerHandler(serverCtx),
			},
		},
	)
}
