// Code generated by goctl. DO NOT EDIT.
// Source: information.proto

package server

import (
	"context"

	"go-micro/platform/information/rpc/information"
	"go-micro/platform/information/rpc/internal/logic/informationservice"
	"go-micro/platform/information/rpc/internal/svc"
)

type InformationServiceServer struct {
	svcCtx *svc.ServiceContext
	information.UnimplementedInformationServiceServer
}

func NewInformationServiceServer(svcCtx *svc.ServiceContext) *InformationServiceServer {
	return &InformationServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *InformationServiceServer) Ping(ctx context.Context, in *information.Request) (*information.Response, error) {
	l := informationservicelogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
