// Code generated by goctl. DO NOT EDIT.
// Source: basic.proto

package basiccategoryservice

import (
	"context"

	"go-micro/platform/basic/rpc/basic"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCategoryRequest             = basic.AddCategoryRequest
	AddCategoryResponse            = basic.AddCategoryResponse
	AddClassifyRequest             = basic.AddClassifyRequest
	AddClassifyResponse            = basic.AddClassifyResponse
	AddConfigurationRequest        = basic.AddConfigurationRequest
	AddConfigurationResponse       = basic.AddConfigurationResponse
	AddIndustryRequest             = basic.AddIndustryRequest
	AddIndustryResponse            = basic.AddIndustryResponse
	AddRegionRequest               = basic.AddRegionRequest
	AddRegionResponse              = basic.AddRegionResponse
	AddStageRequest                = basic.AddStageRequest
	AddStageResponse               = basic.AddStageResponse
	Configuration                  = basic.Configuration
	DeleteCategoryRequest          = basic.DeleteCategoryRequest
	DeleteCategoryResponse         = basic.DeleteCategoryResponse
	DeleteClassifyRequest          = basic.DeleteClassifyRequest
	DeleteClassifyResponse         = basic.DeleteClassifyResponse
	DeleteConfigurationRequest     = basic.DeleteConfigurationRequest
	DeleteConfigurationResponse    = basic.DeleteConfigurationResponse
	DeleteIndustryRequest          = basic.DeleteIndustryRequest
	DeleteIndustryResponse         = basic.DeleteIndustryResponse
	DeleteRegionRequest            = basic.DeleteRegionRequest
	DeleteRegionResponse           = basic.DeleteRegionResponse
	DeleteStageRequest             = basic.DeleteStageRequest
	DeleteStageResponse            = basic.DeleteStageResponse
	GetCategoriesRequest           = basic.GetCategoriesRequest
	GetCategoriesResponse          = basic.GetCategoriesResponse
	GetCategoryChild               = basic.GetCategoryChild
	GetCategoryRequest             = basic.GetCategoryRequest
	GetCategoryResponse            = basic.GetCategoryResponse
	GetClassifiesRequest           = basic.GetClassifiesRequest
	GetClassifiesResponse          = basic.GetClassifiesResponse
	GetClassifyChild               = basic.GetClassifyChild
	GetClassifyRequest             = basic.GetClassifyRequest
	GetClassifyResponse            = basic.GetClassifyResponse
	GetConfigurationByNameRequest  = basic.GetConfigurationByNameRequest
	GetConfigurationRequest        = basic.GetConfigurationRequest
	GetConfigurationResponse       = basic.GetConfigurationResponse
	GetConfigurationsRequest       = basic.GetConfigurationsRequest
	GetConfigurationsResponse      = basic.GetConfigurationsResponse
	GetIndustriesRequest           = basic.GetIndustriesRequest
	GetIndustriesResponse          = basic.GetIndustriesResponse
	GetIndustryByIndustryIdRequest = basic.GetIndustryByIndustryIdRequest
	GetIndustryChild               = basic.GetIndustryChild
	GetIndustryRequest             = basic.GetIndustryRequest
	GetIndustryResponse            = basic.GetIndustryResponse
	GetRegionChild                 = basic.GetRegionChild
	GetRegionRequest               = basic.GetRegionRequest
	GetRegionResponse              = basic.GetRegionResponse
	GetRegionsRequest              = basic.GetRegionsRequest
	GetRegionsResponse             = basic.GetRegionsResponse
	GetStageChild                  = basic.GetStageChild
	GetStageRequest                = basic.GetStageRequest
	GetStageResponse               = basic.GetStageResponse
	GetStagesRequest               = basic.GetStagesRequest
	GetStagesResponse              = basic.GetStagesResponse
	Request                        = basic.Request
	Response                       = basic.Response
	UpdateCategoryRequest          = basic.UpdateCategoryRequest
	UpdateCategoryResponse         = basic.UpdateCategoryResponse
	UpdateClassifyRequest          = basic.UpdateClassifyRequest
	UpdateClassifyResponse         = basic.UpdateClassifyResponse
	UpdateConfigurationRequest     = basic.UpdateConfigurationRequest
	UpdateConfigurationResponse    = basic.UpdateConfigurationResponse
	UpdateIndustryRequest          = basic.UpdateIndustryRequest
	UpdateIndustryResponse         = basic.UpdateIndustryResponse
	UpdateRegionRequest            = basic.UpdateRegionRequest
	UpdateRegionResponse           = basic.UpdateRegionResponse
	UpdateStageRequest             = basic.UpdateStageRequest
	UpdateStageResponse            = basic.UpdateStageResponse

	BasicCategoryService interface {
		// 获取类别信息
		GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error)
		// 根据父级id获取类别信息
		GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
		// 添加类别信息
		AddCategory(ctx context.Context, in *AddCategoryRequest, opts ...grpc.CallOption) (*AddCategoryResponse, error)
		// 更新类别信息
		UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
		// 删除类别信息
		DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
	}

	defaultBasicCategoryService struct {
		cli zrpc.Client
	}
)

func NewBasicCategoryService(cli zrpc.Client) BasicCategoryService {
	return &defaultBasicCategoryService{
		cli: cli,
	}
}

// 获取类别信息
func (m *defaultBasicCategoryService) GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error) {
	client := basic.NewBasicCategoryServiceClient(m.cli.Conn())
	return client.GetCategory(ctx, in, opts...)
}

// 根据父级id获取类别信息
func (m *defaultBasicCategoryService) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	client := basic.NewBasicCategoryServiceClient(m.cli.Conn())
	return client.GetCategories(ctx, in, opts...)
}

// 添加类别信息
func (m *defaultBasicCategoryService) AddCategory(ctx context.Context, in *AddCategoryRequest, opts ...grpc.CallOption) (*AddCategoryResponse, error) {
	client := basic.NewBasicCategoryServiceClient(m.cli.Conn())
	return client.AddCategory(ctx, in, opts...)
}

// 更新类别信息
func (m *defaultBasicCategoryService) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	client := basic.NewBasicCategoryServiceClient(m.cli.Conn())
	return client.UpdateCategory(ctx, in, opts...)
}

// 删除类别信息
func (m *defaultBasicCategoryService) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	client := basic.NewBasicCategoryServiceClient(m.cli.Conn())
	return client.DeleteCategory(ctx, in, opts...)
}
