// Code generated by goctl. DO NOT EDIT.
// Source: basic.proto

package basicindustryservice

import (
	"context"

	"go-micro/platform/basic/rpc/basic"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCategoryRequest             = basic.AddCategoryRequest
	AddCategoryResponse            = basic.AddCategoryResponse
	AddClassifyRequest             = basic.AddClassifyRequest
	AddClassifyResponse            = basic.AddClassifyResponse
	AddConfigurationRequest        = basic.AddConfigurationRequest
	AddConfigurationResponse       = basic.AddConfigurationResponse
	AddIndustryRequest             = basic.AddIndustryRequest
	AddIndustryResponse            = basic.AddIndustryResponse
	AddRegionRequest               = basic.AddRegionRequest
	AddRegionResponse              = basic.AddRegionResponse
	AddStageRequest                = basic.AddStageRequest
	AddStageResponse               = basic.AddStageResponse
	Configuration                  = basic.Configuration
	DeleteCategoryRequest          = basic.DeleteCategoryRequest
	DeleteCategoryResponse         = basic.DeleteCategoryResponse
	DeleteClassifyRequest          = basic.DeleteClassifyRequest
	DeleteClassifyResponse         = basic.DeleteClassifyResponse
	DeleteConfigurationRequest     = basic.DeleteConfigurationRequest
	DeleteConfigurationResponse    = basic.DeleteConfigurationResponse
	DeleteIndustryRequest          = basic.DeleteIndustryRequest
	DeleteIndustryResponse         = basic.DeleteIndustryResponse
	DeleteRegionRequest            = basic.DeleteRegionRequest
	DeleteRegionResponse           = basic.DeleteRegionResponse
	DeleteStageRequest             = basic.DeleteStageRequest
	DeleteStageResponse            = basic.DeleteStageResponse
	GetCategoriesRequest           = basic.GetCategoriesRequest
	GetCategoriesResponse          = basic.GetCategoriesResponse
	GetCategoryChild               = basic.GetCategoryChild
	GetCategoryRequest             = basic.GetCategoryRequest
	GetCategoryResponse            = basic.GetCategoryResponse
	GetClassifiesRequest           = basic.GetClassifiesRequest
	GetClassifiesResponse          = basic.GetClassifiesResponse
	GetClassifyChild               = basic.GetClassifyChild
	GetClassifyRequest             = basic.GetClassifyRequest
	GetClassifyResponse            = basic.GetClassifyResponse
	GetConfigurationByNameRequest  = basic.GetConfigurationByNameRequest
	GetConfigurationRequest        = basic.GetConfigurationRequest
	GetConfigurationResponse       = basic.GetConfigurationResponse
	GetConfigurationsRequest       = basic.GetConfigurationsRequest
	GetConfigurationsResponse      = basic.GetConfigurationsResponse
	GetIndustriesRequest           = basic.GetIndustriesRequest
	GetIndustriesResponse          = basic.GetIndustriesResponse
	GetIndustryByIndustryIdRequest = basic.GetIndustryByIndustryIdRequest
	GetIndustryChild               = basic.GetIndustryChild
	GetIndustryRequest             = basic.GetIndustryRequest
	GetIndustryResponse            = basic.GetIndustryResponse
	GetRegionChild                 = basic.GetRegionChild
	GetRegionRequest               = basic.GetRegionRequest
	GetRegionResponse              = basic.GetRegionResponse
	GetRegionsRequest              = basic.GetRegionsRequest
	GetRegionsResponse             = basic.GetRegionsResponse
	GetStageChild                  = basic.GetStageChild
	GetStageRequest                = basic.GetStageRequest
	GetStageResponse               = basic.GetStageResponse
	GetStagesRequest               = basic.GetStagesRequest
	GetStagesResponse              = basic.GetStagesResponse
	Request                        = basic.Request
	Response                       = basic.Response
	UpdateCategoryRequest          = basic.UpdateCategoryRequest
	UpdateCategoryResponse         = basic.UpdateCategoryResponse
	UpdateClassifyRequest          = basic.UpdateClassifyRequest
	UpdateClassifyResponse         = basic.UpdateClassifyResponse
	UpdateConfigurationRequest     = basic.UpdateConfigurationRequest
	UpdateConfigurationResponse    = basic.UpdateConfigurationResponse
	UpdateIndustryRequest          = basic.UpdateIndustryRequest
	UpdateIndustryResponse         = basic.UpdateIndustryResponse
	UpdateRegionRequest            = basic.UpdateRegionRequest
	UpdateRegionResponse           = basic.UpdateRegionResponse
	UpdateStageRequest             = basic.UpdateStageRequest
	UpdateStageResponse            = basic.UpdateStageResponse

	BasicIndustryService interface {
		// 获取职业信息
		GetIndustry(ctx context.Context, in *GetIndustryRequest, opts ...grpc.CallOption) (*GetIndustryResponse, error)
		// 根据industry_id获取职业信息
		GetIndustryByIndustryId(ctx context.Context, in *GetIndustryByIndustryIdRequest, opts ...grpc.CallOption) (*GetIndustryResponse, error)
		// 根据父级id获取职业信息
		GetIndustries(ctx context.Context, in *GetIndustriesRequest, opts ...grpc.CallOption) (*GetIndustriesResponse, error)
		// 添加职业信息
		AddIndustry(ctx context.Context, in *AddIndustryRequest, opts ...grpc.CallOption) (*AddIndustryResponse, error)
		// 更新职业信息
		UpdateIndustry(ctx context.Context, in *UpdateIndustryRequest, opts ...grpc.CallOption) (*UpdateIndustryResponse, error)
		// 删除职业信息
		DeleteIndustry(ctx context.Context, in *DeleteIndustryRequest, opts ...grpc.CallOption) (*DeleteIndustryResponse, error)
	}

	defaultBasicIndustryService struct {
		cli zrpc.Client
	}
)

func NewBasicIndustryService(cli zrpc.Client) BasicIndustryService {
	return &defaultBasicIndustryService{
		cli: cli,
	}
}

// 获取职业信息
func (m *defaultBasicIndustryService) GetIndustry(ctx context.Context, in *GetIndustryRequest, opts ...grpc.CallOption) (*GetIndustryResponse, error) {
	client := basic.NewBasicIndustryServiceClient(m.cli.Conn())
	return client.GetIndustry(ctx, in, opts...)
}

// 根据industry_id获取职业信息
func (m *defaultBasicIndustryService) GetIndustryByIndustryId(ctx context.Context, in *GetIndustryByIndustryIdRequest, opts ...grpc.CallOption) (*GetIndustryResponse, error) {
	client := basic.NewBasicIndustryServiceClient(m.cli.Conn())
	return client.GetIndustryByIndustryId(ctx, in, opts...)
}

// 根据父级id获取职业信息
func (m *defaultBasicIndustryService) GetIndustries(ctx context.Context, in *GetIndustriesRequest, opts ...grpc.CallOption) (*GetIndustriesResponse, error) {
	client := basic.NewBasicIndustryServiceClient(m.cli.Conn())
	return client.GetIndustries(ctx, in, opts...)
}

// 添加职业信息
func (m *defaultBasicIndustryService) AddIndustry(ctx context.Context, in *AddIndustryRequest, opts ...grpc.CallOption) (*AddIndustryResponse, error) {
	client := basic.NewBasicIndustryServiceClient(m.cli.Conn())
	return client.AddIndustry(ctx, in, opts...)
}

// 更新职业信息
func (m *defaultBasicIndustryService) UpdateIndustry(ctx context.Context, in *UpdateIndustryRequest, opts ...grpc.CallOption) (*UpdateIndustryResponse, error) {
	client := basic.NewBasicIndustryServiceClient(m.cli.Conn())
	return client.UpdateIndustry(ctx, in, opts...)
}

// 删除职业信息
func (m *defaultBasicIndustryService) DeleteIndustry(ctx context.Context, in *DeleteIndustryRequest, opts ...grpc.CallOption) (*DeleteIndustryResponse, error) {
	client := basic.NewBasicIndustryServiceClient(m.cli.Conn())
	return client.DeleteIndustry(ctx, in, opts...)
}
