// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-micro/mall/gateway/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/gateway/getOrder/:id",
				Handler: getOrderHandler(serverCtx),
			},
		},
	)
}
