// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	systemRegionFieldNames          = builder.RawFieldNames(&SystemRegion{})
	systemRegionRows                = strings.Join(systemRegionFieldNames, ",")
	systemRegionRowsExpectAutoSet   = strings.Join(stringx.Remove(systemRegionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	systemRegionRowsWithPlaceHolder = strings.Join(stringx.Remove(systemRegionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSystemRegionIdPrefix = "cache:systemRegion:id:"
)

type (
	systemRegionModel interface {
		Insert(ctx context.Context, data *SystemRegion) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SystemRegion, error)
		Update(ctx context.Context, data *SystemRegion) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSystemRegionModel struct {
		sqlc.CachedConn
		table string
	}

	SystemRegion struct {
		Id       int64  `db:"id"`        // 主键id
		ParentId int64  `db:"parent_id"` // 父级id
		Name     string `db:"name"`      // 区域id
	}
)

func newSystemRegionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSystemRegionModel {
	return &defaultSystemRegionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`system_region`",
	}
}

func (m *defaultSystemRegionModel) Delete(ctx context.Context, id int64) error {
	systemRegionIdKey := fmt.Sprintf("%s%v", cacheSystemRegionIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, systemRegionIdKey)
	return err
}

func (m *defaultSystemRegionModel) FindOne(ctx context.Context, id int64) (*SystemRegion, error) {
	systemRegionIdKey := fmt.Sprintf("%s%v", cacheSystemRegionIdPrefix, id)
	var resp SystemRegion
	err := m.QueryRowCtx(ctx, &resp, systemRegionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", systemRegionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemRegionModel) Insert(ctx context.Context, data *SystemRegion) (sql.Result, error) {
	systemRegionIdKey := fmt.Sprintf("%s%v", cacheSystemRegionIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, systemRegionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ParentId, data.Name)
	}, systemRegionIdKey)
	return ret, err
}

func (m *defaultSystemRegionModel) Update(ctx context.Context, data *SystemRegion) error {
	systemRegionIdKey := fmt.Sprintf("%s%v", cacheSystemRegionIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, systemRegionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ParentId, data.Name, data.Id)
	}, systemRegionIdKey)
	return err
}

func (m *defaultSystemRegionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSystemRegionIdPrefix, primary)
}

func (m *defaultSystemRegionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", systemRegionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSystemRegionModel) tableName() string {
	return m.table
}
