// Code generated by goctl. DO NOT EDIT.
package types

type GatewayGetRegionRequest struct {
	Id int64 `path:"id"`
}

type GatewayGetRegionReply struct {
	Id       int64  `json:"id"`
	ParentId int64  `json:"parent_id"`
	Name     string `json:"name"`
}

type GatewayGetRegionsRequest struct {
	ParentId int64 `path:"parent_id"`
}

type GatewayGetRegionsReply struct {
	List []GatewayGetRegionsChild `json:"list"`
}

type GatewayGetRegionsChild struct {
	Id       int64  `json:"id"`
	ParentId int64  `json:"parent_id"`
	Name     string `json:"name"`
}

type GatewayAddRegionRequest struct {
	ParentId int64  `json:"parent_id"`
	Name     string `json:"name"`
}

type GatewayAddRegionReply struct {
	Id       int64  `json:"id"`
	ParentId int64  `json:"parent_id"`
	Name     string `json:"name"`
}

type GatewayRegisterRequest struct {
	Mobile   string `json:"mobile"`
	Email    string `json:"email"`
	Password string `json:"password"`
	AuthKey  string `json:"auth_key"`
	AuthType string `json:"auth_type"`
}

type GatewayRegisterResponse struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}
