// Code generated by goctl. DO NOT EDIT.
// Source: information.proto

package informationtopicauditrecordservice

import (
	"context"

	"go-micro/platform/information/rpc/information"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddTopicAuditRecordRequest  = information.AddTopicAuditRecordRequest
	AddTopicAuditRecordResponse = information.AddTopicAuditRecordResponse
	AddTopicRequest             = information.AddTopicRequest
	AddTopicResponse            = information.AddTopicResponse
	DeleteTopicRequest          = information.DeleteTopicRequest
	DeleteTopicResponse         = information.DeleteTopicResponse
	GetTopicAuditRecordRequest  = information.GetTopicAuditRecordRequest
	GetTopicAuditRecordResponse = information.GetTopicAuditRecordResponse
	GetTopicRequest             = information.GetTopicRequest
	GetTopicResponse            = information.GetTopicResponse
	GetTopicsRequest            = information.GetTopicsRequest
	GetTopicsResponse           = information.GetTopicsResponse
	Request                     = information.Request
	Response                    = information.Response
	Topic                       = information.Topic
	UpdateTopicRequest          = information.UpdateTopicRequest
	UpdateTopicResponse         = information.UpdateTopicResponse

	InformationTopicAuditRecordService interface {
		// 添加文章审核记录
		AddTopicAuditRecord(ctx context.Context, in *AddTopicAuditRecordRequest, opts ...grpc.CallOption) (*AddTopicAuditRecordResponse, error)
		// 获取文章审核记录
		GetTopicAuditRecord(ctx context.Context, in *GetTopicAuditRecordRequest, opts ...grpc.CallOption) (*GetTopicAuditRecordResponse, error)
	}

	defaultInformationTopicAuditRecordService struct {
		cli zrpc.Client
	}
)

func NewInformationTopicAuditRecordService(cli zrpc.Client) InformationTopicAuditRecordService {
	return &defaultInformationTopicAuditRecordService{
		cli: cli,
	}
}

// 添加文章审核记录
func (m *defaultInformationTopicAuditRecordService) AddTopicAuditRecord(ctx context.Context, in *AddTopicAuditRecordRequest, opts ...grpc.CallOption) (*AddTopicAuditRecordResponse, error) {
	client := information.NewInformationTopicAuditRecordServiceClient(m.cli.Conn())
	return client.AddTopicAuditRecord(ctx, in, opts...)
}

// 获取文章审核记录
func (m *defaultInformationTopicAuditRecordService) GetTopicAuditRecord(ctx context.Context, in *GetTopicAuditRecordRequest, opts ...grpc.CallOption) (*GetTopicAuditRecordResponse, error) {
	client := information.NewInformationTopicAuditRecordServiceClient(m.cli.Conn())
	return client.GetTopicAuditRecord(ctx, in, opts...)
}
