// Code generated by goctl. DO NOT EDIT.
// Source: basic.proto

package basicconfigurationservice

import (
	"context"

	"go-micro/platform/basic/rpc/basic"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCategoryRequest             = basic.AddCategoryRequest
	AddCategoryResponse            = basic.AddCategoryResponse
	AddClassifyRequest             = basic.AddClassifyRequest
	AddClassifyResponse            = basic.AddClassifyResponse
	AddConfigurationRequest        = basic.AddConfigurationRequest
	AddConfigurationResponse       = basic.AddConfigurationResponse
	AddIndustryRequest             = basic.AddIndustryRequest
	AddIndustryResponse            = basic.AddIndustryResponse
	AddRegionRequest               = basic.AddRegionRequest
	AddRegionResponse              = basic.AddRegionResponse
	AddStageRequest                = basic.AddStageRequest
	AddStageResponse               = basic.AddStageResponse
	Configuration                  = basic.Configuration
	DeleteCategoryRequest          = basic.DeleteCategoryRequest
	DeleteCategoryResponse         = basic.DeleteCategoryResponse
	DeleteClassifyRequest          = basic.DeleteClassifyRequest
	DeleteClassifyResponse         = basic.DeleteClassifyResponse
	DeleteConfigurationRequest     = basic.DeleteConfigurationRequest
	DeleteConfigurationResponse    = basic.DeleteConfigurationResponse
	DeleteIndustryRequest          = basic.DeleteIndustryRequest
	DeleteIndustryResponse         = basic.DeleteIndustryResponse
	DeleteRegionRequest            = basic.DeleteRegionRequest
	DeleteRegionResponse           = basic.DeleteRegionResponse
	DeleteStageRequest             = basic.DeleteStageRequest
	DeleteStageResponse            = basic.DeleteStageResponse
	GetCategoriesRequest           = basic.GetCategoriesRequest
	GetCategoriesResponse          = basic.GetCategoriesResponse
	GetCategoryChild               = basic.GetCategoryChild
	GetCategoryRequest             = basic.GetCategoryRequest
	GetCategoryResponse            = basic.GetCategoryResponse
	GetClassifiesRequest           = basic.GetClassifiesRequest
	GetClassifiesResponse          = basic.GetClassifiesResponse
	GetClassifyChild               = basic.GetClassifyChild
	GetClassifyRequest             = basic.GetClassifyRequest
	GetClassifyResponse            = basic.GetClassifyResponse
	GetConfigurationByNameRequest  = basic.GetConfigurationByNameRequest
	GetConfigurationRequest        = basic.GetConfigurationRequest
	GetConfigurationResponse       = basic.GetConfigurationResponse
	GetConfigurationsRequest       = basic.GetConfigurationsRequest
	GetConfigurationsResponse      = basic.GetConfigurationsResponse
	GetIndustriesRequest           = basic.GetIndustriesRequest
	GetIndustriesResponse          = basic.GetIndustriesResponse
	GetIndustryByIndustryIdRequest = basic.GetIndustryByIndustryIdRequest
	GetIndustryChild               = basic.GetIndustryChild
	GetIndustryRequest             = basic.GetIndustryRequest
	GetIndustryResponse            = basic.GetIndustryResponse
	GetRegionChild                 = basic.GetRegionChild
	GetRegionRequest               = basic.GetRegionRequest
	GetRegionResponse              = basic.GetRegionResponse
	GetRegionsRequest              = basic.GetRegionsRequest
	GetRegionsResponse             = basic.GetRegionsResponse
	GetStageChild                  = basic.GetStageChild
	GetStageRequest                = basic.GetStageRequest
	GetStageResponse               = basic.GetStageResponse
	GetStagesRequest               = basic.GetStagesRequest
	GetStagesResponse              = basic.GetStagesResponse
	Request                        = basic.Request
	Response                       = basic.Response
	UpdateCategoryRequest          = basic.UpdateCategoryRequest
	UpdateCategoryResponse         = basic.UpdateCategoryResponse
	UpdateClassifyRequest          = basic.UpdateClassifyRequest
	UpdateClassifyResponse         = basic.UpdateClassifyResponse
	UpdateConfigurationRequest     = basic.UpdateConfigurationRequest
	UpdateConfigurationResponse    = basic.UpdateConfigurationResponse
	UpdateIndustryRequest          = basic.UpdateIndustryRequest
	UpdateIndustryResponse         = basic.UpdateIndustryResponse
	UpdateRegionRequest            = basic.UpdateRegionRequest
	UpdateRegionResponse           = basic.UpdateRegionResponse
	UpdateStageRequest             = basic.UpdateStageRequest
	UpdateStageResponse            = basic.UpdateStageResponse

	BasicConfigurationService interface {
		// 获取配置信息
		GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error)
		// 根据配置名称获取配置信息
		GetConfigurationByName(ctx context.Context, in *GetConfigurationByNameRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error)
		// 获取配置列表
		GetConfigurations(ctx context.Context, in *GetConfigurationsRequest, opts ...grpc.CallOption) (*GetConfigurationsResponse, error)
		// 添加配置信息
		AddConfiguration(ctx context.Context, in *AddConfigurationRequest, opts ...grpc.CallOption) (*AddConfigurationResponse, error)
		// 更新配置信息
		UpdateConfiguration(ctx context.Context, in *UpdateConfigurationRequest, opts ...grpc.CallOption) (*UpdateConfigurationResponse, error)
		// 删除配置信息
		DeleteConfiguration(ctx context.Context, in *DeleteConfigurationRequest, opts ...grpc.CallOption) (*DeleteConfigurationResponse, error)
	}

	defaultBasicConfigurationService struct {
		cli zrpc.Client
	}
)

func NewBasicConfigurationService(cli zrpc.Client) BasicConfigurationService {
	return &defaultBasicConfigurationService{
		cli: cli,
	}
}

// 获取配置信息
func (m *defaultBasicConfigurationService) GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error) {
	client := basic.NewBasicConfigurationServiceClient(m.cli.Conn())
	return client.GetConfiguration(ctx, in, opts...)
}

// 根据配置名称获取配置信息
func (m *defaultBasicConfigurationService) GetConfigurationByName(ctx context.Context, in *GetConfigurationByNameRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error) {
	client := basic.NewBasicConfigurationServiceClient(m.cli.Conn())
	return client.GetConfigurationByName(ctx, in, opts...)
}

// 获取配置列表
func (m *defaultBasicConfigurationService) GetConfigurations(ctx context.Context, in *GetConfigurationsRequest, opts ...grpc.CallOption) (*GetConfigurationsResponse, error) {
	client := basic.NewBasicConfigurationServiceClient(m.cli.Conn())
	return client.GetConfigurations(ctx, in, opts...)
}

// 添加配置信息
func (m *defaultBasicConfigurationService) AddConfiguration(ctx context.Context, in *AddConfigurationRequest, opts ...grpc.CallOption) (*AddConfigurationResponse, error) {
	client := basic.NewBasicConfigurationServiceClient(m.cli.Conn())
	return client.AddConfiguration(ctx, in, opts...)
}

// 更新配置信息
func (m *defaultBasicConfigurationService) UpdateConfiguration(ctx context.Context, in *UpdateConfigurationRequest, opts ...grpc.CallOption) (*UpdateConfigurationResponse, error) {
	client := basic.NewBasicConfigurationServiceClient(m.cli.Conn())
	return client.UpdateConfiguration(ctx, in, opts...)
}

// 删除配置信息
func (m *defaultBasicConfigurationService) DeleteConfiguration(ctx context.Context, in *DeleteConfigurationRequest, opts ...grpc.CallOption) (*DeleteConfigurationResponse, error) {
	client := basic.NewBasicConfigurationServiceClient(m.cli.Conn())
	return client.DeleteConfiguration(ctx, in, opts...)
}
