// Code generated by goctl. DO NOT EDIT.
// Source: basic.proto

package server

import (
	"context"

	"go-micro/platform/basic/rpc/basic"
	"go-micro/platform/basic/rpc/internal/logic"
	"go-micro/platform/basic/rpc/internal/svc"
)

type BasicServer struct {
	svcCtx *svc.ServiceContext
	basic.UnimplementedBasicServer
}

func NewBasicServer(svcCtx *svc.ServiceContext) *BasicServer {
	return &BasicServer{
		svcCtx: svcCtx,
	}
}

func (s *BasicServer) Ping(ctx context.Context, in *basic.Request) (*basic.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *BasicServer) GetRegion(ctx context.Context, in *basic.GetRegionRequest) (*basic.GetRegionResponse, error) {
	l := logic.NewGetRegionLogic(ctx, s.svcCtx)
	return l.GetRegion(in)
}

func (s *BasicServer) GetRegions(ctx context.Context, in *basic.GetRegionsRequest) (*basic.GetRegionsResponse, error) {
	l := logic.NewGetRegionsLogic(ctx, s.svcCtx)
	return l.GetRegions(in)
}

func (s *BasicServer) AddRegion(ctx context.Context, in *basic.AddRegionRequest) (*basic.AddRegionResponse, error) {
	l := logic.NewAddRegionLogic(ctx, s.svcCtx)
	return l.AddRegion(in)
}
